config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :calculations
  get 'home/index'
  root 'home#index'
  get 'home/about'
  post 'get_compound_interest', to: 'calculations#get_compound_interest'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/calculation.rb
class Calculation < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

         has_many :friends
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/calculations_controller.rb
class CalculationsController < ApplicationController
  before_action :set_calculation, only: %i[ show edit update destroy ]
  before_action :authenticate_user!, except: [:get_compound_interest]
  skip_before_action :verify_authenticity_token

  # GET /calculations or /calculations.json
  def index
    # @calculations = Calculation.all
    @calculations = Calculation.where(user_id: current_user.id)
  end

  # GET /calculations/1 or /calculations/1.json
  def show
  end

  # GET /calculations/new
  def new
    @calculation = Calculation.new
  end

  def get_compound_interest
    @calculation = Calculation.new
    valid = true
    message = ""

    principal = params[:principal].to_f
    interest_rate = params[:interest_rate].to_f / 100
    years = params[:years].to_i

    #once per year for now
    compounds_per_year = 1

    result = CalculationsHelper.calculate_result(principal, interest_rate, years, compounds_per_year)
    
    rounded_result = result.round(2)

    # Rails.logger.debug "result" 
    # Rails.logger.debug result     
    # Rails.logger.debug "rounded_result" 
    # Rails.logger.debug rounded_result 

    data = {
        valid: valid,
        message: message,
        result: rounded_result
    }

    render json: data.to_json

  end

  # GET /calculations/1/edit
  def edit
  end

  # POST /calculations or /calculations.json
  def create
    @calculation = Calculation.new(calculation_params)

    principal = calculation_params[:principal].to_f
    interest_rate = calculation_params[:interest_rate].to_f / 100
    years = calculation_params[:years].to_i
    compounds_per_year = 1

    result = CalculationsHelper.calculate_result(principal, interest_rate, years, compounds_per_year)
    rounded_result = result.round(2)

    # Rails.logger.debug "result" 
    # Rails.logger.debug result 
    # Rails.logger.debug "@calculation" 
    # Rails.logger.debug pp(@calculation)

    @calculation.result = rounded_result

    respond_to do |format|
      if @calculation.save
        format.html { redirect_to @calculation, notice: "Calculation was successfully created." }
        format.json { render :show, status: :created, location: @calculation }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @calculation.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /calculations/1 or /calculations/1.json
  def update

    principal = calculation_params[:principal].to_f
    interest_rate = calculation_params[:interest_rate].to_f / 100
    years = calculation_params[:years].to_i
    compounds_per_year = 1

    new_result = CalculationsHelper.calculate_result(principal, interest_rate, years, compounds_per_year)
    rounded_result = new_result.round(2)

    # Rails.logger.debug "result - update" 
    # Rails.logger.debug new_result 
    # Rails.logger.debug "@calculation - update" 
    # Rails.logger.debug pp(@calculation)

    @calculation.result = rounded_result
    respond_to do |format|
      if @calculation.update(calculation_params)
        format.html { redirect_to @calculation, notice: "Calculation was successfully updated." }
        format.json { render :show, status: :ok, location: @calculation }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @calculation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /calculations/1 or /calculations/1.json
  def destroy
    @calculation.destroy
    respond_to do |format|
      format.html { redirect_to calculations_url, notice: "Calculation was successfully destroyed." }
      format.json { head :no_content }
    end
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_calculation
      @calculation = Calculation.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def calculation_params
      params.require(:calculation).permit(:name, :currency, :principal, :interest_rate, :years, :user_id)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
  
  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/calculations_helper.rb
module CalculationsHelper

  def self.calculate_result(principal, interest_rate, years, compounds_per_year)
    result = principal * ((1 + interest_rate) ** (compounds_per_year * years))
    
    return result 
  end

end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/calculations/_form.html.erb
<%= form_with(model: calculation) do |form| %>
  <% if calculation.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(calculation.errors.count, "error") %> prohibited this calculation from being saved:</h2>

      <ul>
        <% calculation.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field mb-3">
    <%  form.label :name %>
    <%= form.text_field :name, class:"form-control", placeholder:"Name" %>
  </div>

  <div class="field mb-3">
    <%  form.label :principal %>
    <%= form.text_field :currency, class:"form-control", placeholder:"Currency" %>
  </div>

  <div class="field mb-3">
    <%  form.label :principal %>
    <%= form.text_field :principal, class:"form-control", placeholder:"Principal (Initial value)" %>
  </div>

  <div class="field mb-3">
    <%  form.label :interest_rate %>
    <%= form.text_field :interest_rate, class:"form-control", placeholder:"Interest Rate" %>
  </div>

  <div class="field mb-3">
    <%  form.label :years %>
    <%= form.number_field :years, class:"form-control", placeholder:"Years" %>
  </div>

  <div class="actions">    
    <%= form.submit "Save Calculation", class:"btn btn-primary"%>
  </div>
<% end %>

app/views/calculations/edit.html.erb
<h1>Editing Calculation</h1>

<%= render 'form', calculation: @calculation %>

<%= link_to 'Show', @calculation %> |
<%= link_to 'Back', calculations_path %>

app/views/calculations/index.html.erb
<h1>Calculations</h1>

<table class="table table-striped table-bordered table-hover">
  <thead class="table-dark">
    <tr>
      <th>Name</th>
      <th>Currency</th>
      <th>Principal</th>
      <th>Interest rate</th>
      <th>Years</th>
      <th>Result</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @calculations.each do |calculation| %>
      <tr>
        <td><%= calculation.name %></td>
        <td><%= calculation.currency %></td>
        <td><%= calculation.principal %></td>
        <td><%= calculation.interest_rate %></td>
        <td><%= calculation.years %></td>
        <td><%= calculation.result %></td>
        <td><%= link_to 'Show', calculation %></td>
        <td><%= link_to 'Edit', edit_calculation_path(calculation) %></td>
        <td><%= link_to 'Destroy', calculation, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Calculator', root_path, class:"btn btn-primary", method: :get %>

app/views/calculations/new.html.erb
<h1>New Calculation</h1>

<%= render 'form', calculation: @calculation %>

<%= link_to 'Back', calculations_path %>

app/views/calculations/show.html.erb
<div class="bg-light p-5 rounded-lg m-3">

  <% currency_symbol = @calculation.currency == "GBP" ? "£" : @calculation.currency == "USD" ? "$" : "€" %>

  <h1 class="display-4">
    <%= @calculation.name %>
  </h1>
  <p class="lead">
    <strong>Principal:</strong><%= @calculation.principal %> 
  </p>
  <p class="lead">
    <strong>Interest rate:</strong><%= @calculation.interest_rate %>  
  </p>
  <p class="lead">
    <strong>Years:</strong><%= @calculation.years %> 
  </p>
  <hr class="my-4">
  <p class="lead">
    <p><%="After #{@calculation.years} years, with an interest rate of #{@calculation.interest_rate}% compounding annually, your #{currency_symbol}#{@calculation.principal} will grow to:"%></p>
    <h2><%="#{currency_symbol}#{@calculation.result}"%></h2> 
  </p>
  <%= link_to 'My Calculations', calculations_path, class:"btn btn-dark" %>
  <%= link_to 'Delete', @calculation, method: :delete, data: { confirm: 'Are you sure?' }, class:"btn btn-danger" %>
 </div>

app/views/home/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    <%= link_to 'CompoundInterest', root_path, class:"navbar-brand", method: :get %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <% if user_signed_in? %>
          <li class="nav-item">
            <%= link_to 'Calculator', root_path, class:"nav-link", method: :get %>
          </li>
          <li class="nav-item">
            <%= link_to 'My Calculations', calculations_path, class:"nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to 'Sign Out', destroy_user_session_path, method: :delete, class:"nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to 'Edit Profile', edit_user_registration_path, class:"nav-link" %>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to 'Sign Up', new_user_registration_path, class:"nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to 'Sign In', new_user_session_path, class:"nav-link" %>
          </li>
        <% end %>
        <li class="nav-item">
          <%= link_to 'About', home_about_path, class:"nav-link" %>
        </li>  
      </ul>
    </div>
  </div>
</nav> 

app/views/home/about.html.erb
<h1>Compound Interest Calculator</h1>
<p>Hi, welcome to this compound interest calculator application</p>
<p>This simple application will accept your parameters of your initial sum ( known as the Principal), the rate of interest, and the number of years which will pass.
<p>It will return the future value of your investment based on the data you enter.</p>

app/views/home/index.html.erb
<%= javascript_pack_tag 'hello_react' %>

<%= content_tag :div,
    id: "user_data",
    data: current_user.to_json,
    is_signed_in: user_signed_in? do %>
  <% end %>

app/views/layouts/_alerts.html.erb
<div class="alert alert-warning alert-dismissible fade show" role="alert">
  <%= notice %>
  <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div> 

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CompoundInterest</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta charset="utf-8">

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

  </head>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KyZXEAg3QhqLMpG8r+8fhAXLRk2vvoC2f3B09zVXn8CA5QIVfZOJ3BCsw2P0p/We" crossorigin="anonymous">

  <body></body>

    <%= render 'home/header' %>
    <br/>

    <div class="container">
      <% if notice %>
        <%= render 'layouts/alerts'%>
      <% end %>
      <%= yield %>
    </div>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-U1DAWAznBHeqEIlVSCgzq+c9gqGAJn5c/t99JyeKa9xxaYpSvHU5awsuZVVFIhvj" crossorigin="anonymous"></script>

  </body>

</html>